### ISSUE TITLE
How to add an input

### ISSUE THREAD

**Issue by MikeChenfu** [intel/yask#32]
Hello Charles,

I am very interested in this work and I am learning about this framework. I try adding a new stencil into this tool. 
I have a question about how to decide the input data. I check the existed stencils, such as AveStencile and Iso3dfdStencil, but I still have no idea about the location of input data.

Thanks for your help.

**Comment by chuckyount** [comment]
Thanks for your interest in using YASK. When using the existing performance-evaluation utility, the data is initialized with a simple pattern values. Programmers who have used the YASK kernels in larger software projects have provided their own data-initialization code. If you can tell me how you'd like to input your data, I can give you a better idea of how to proceed. For example, do you want to load the data from a file?

**Comment by MikeChenfu** [comment]
Yes, I want to load the data from a file and use the YASK kernel to process them. Thanks.

**Comment by chuckyount** [comment]
[Sorry for the delay; I've been travelling.]
A few possibilities: 
1. One of the contributors to YASK is planning to add generic file I/O. There is no ETA, though, so I can't tell you when this might be available.
2. You can add file I/O specific to your stencil by adding code to your stencil class constructor using the REGISTER_STENCIL_CONTEXT_EXTENSION macro. There is an example in src/foldBuilder/stencils/SSGElasticStencil.hpp. In this macro, you need to define initData() to load the data into your grids using the writeElem() methods defined in src/realv_grids.hpp.
3. If you'd like to contribute to the project, you can propose and develop a generic file I/O capability that will work with any stencil.

In any case, you should probably work from the 'develop' git branch to make sure you're getting the latest code. If you'd like to contribute your stencil, you can make a pull request on this branch.

**Comment by MikeChenfu** [comment]
Thanks for the ideas. I will add  I/O specific to my stencil first and try developing a generic file I/O. I think it will be helpful for other users.

Of course, I can contribute my stencil to the branch when I finish.

**Comment by chuckyount** [comment]
There are now several APIs for initializing data in the 'develop' branch.

**Comment by chuckyount** [comment]
The APIs for initializing data are now in ver 2 in the 'master' branch.
