### ISSUE TITLE
How to initialize a 2D GRID

### ISSUE THREAD

**Issue by MikeChenfu** [intel/yask#33]
Hello,

It fails when I try using INIT_GRID_2D to design a kernel, but I find the INIT_GRID_2D method defined in src/foldBuilder/Expr.hpp.  Is there any way to use INIT_GRID_2D?  Thanks for your help.

**Comment by chuckyount** [comment]
Yes; sorry about that. In general, the stencil DSL compiler (foldBuilder) is more expressive and general than the YASK code itself. Specifically, the compiler supports any grid dimensions up to 6D with any names on those dimensions. But, the YASK code only supports 3D (x, y, z), 4D (t, x, y, z OR w, x, y, z) and 5D (t, w, x, y, z) grids. So, until the YASK code "catches up", you either need to use the supported grid dimensions (with the given dimension names) only or add functionality to the YASK code.

**Comment by MikeChenfu** [comment]
Thanks for the quick reply. I will try it. Thanks again.

**Comment by chuckyount** [comment]
FYI, a large project to generalize dimensions is underway. When that is done, problems with 1D and 2D grids and domains should be no different than 3D ones.

**Comment by chuckyount** [comment]
In version 2, you can now use 2D grids as inputs to 3D stencils.
