### ISSUE TITLE
Failed to add IF conditions to kernel

### ISSUE THREAD

**Issue by MikeChenfu** [intel/yask#34]
Hello,

It fails when I try adding an IF condition in the kernel, such  as  grid(t+1, x, y, z) IS_EQUIV_TO v IF (v == constNum(1.0)). However, it works about grid(t+1, x, y, z) IS_EQUIV_TO v IF (z == last_index(z)). I think both IF conditions return the same type. Do you have any ideas about this problem? Thank you so much.

**Comment by chuckyount** [comment]
Variables in IF conditions can only be indices. They cannot be grid values.

**Comment by MikeChenfu** [comment]
Thanks for your help. Is there any way to emit "grid(t+1, x, y, z) IS_EQUIV_TO v " when the condition "v == constNum(1.0)" is true? I try another method like following code
```
if(v == constNum(1.0))
    grid(t+1, x, y, z) IS_EQUIV_TO v;
```

Even though it can be compiled and running, I do not think the method works. Thank you.

**Comment by chuckyount** [comment]
No, there is no way to make a grid update conditional on a value at this time.

**Comment by chuckyount** [comment]
BTW, it may be helpful to think of the code you write in the define() method as building up an expression as opposed to immediately evaluating it. This might help to explain why you can't expect a 'normal' if-statement to do what you want. You can see what expression you've created by running the stencil compiler (./foldBuilder) with the -ph <filename> option (-ph '-' will print to stdout). This option will print out the expression in a human-readable text. It actually prints two versions--the first as one large expression, and the second with intermediate variables.

**Comment by MikeChenfu** [comment]
Thanks for your kind help. I check the code again and follow your instruction to see human-readable text. If-statement cannot be added to the kernel. Is it possible to add if-statement to other location where to get the output of the kernel in each time step ?

**Comment by chuckyount** [comment]
Sorry about the delayed response. Unfortunately, I don't understand what you need. Do you want to output the data, or are you trying to do something pro grammatically with it?

**Comment by MikeChenfu** [comment]
Thanks for your reply. I know I cannot add a 'normal' if-statement on the kernel but someimes we have to. So I try adding it into the other part instead of the kernel.

**Comment by chuckyount** [comment]
Closing due to lack of actionable tasks.
