### ISSUE TITLE
set_domain_dim_names won't fail

### ISSUE THREAD

**Issue by FabioLuporini** [intel/yask#43]
``set_domain_dim_names(<dimensions>)`` should fail immediately if `t` is provided as domain dimension, but it doesn't

**Comment by chuckyount** [comment]
Since there is a fairly simple workaround, this probably won't be addressed until after a large project generalizing dimensions is pushed.

**Comment by chuckyount** [comment]
This API will gone away in v2. In v2, a dim name is just a node. I'll leave this open because I might still want to catch using repeated dims when creating a grid.

**Comment by chuckyount** [comment]
In ver 2, repeated dims in a grid are now caught as an error. Some other inconsistencies cannot be easily caught until an output format is requested.
