### ISSUE TITLE
make realclean

### ISSUE THREAD

**Issue by FabioLuporini** [intel/yask#45]
it's leaving some useless files under ``/lib``, such as ``devito_ctx0_yk_hook0.py,  devito_ctx0_yk_hook0.pyc, ...``

**Comment by FabioLuporini** [comment]
also, ``yask_compiler.{py,pyc}`` are left in there (you can see this only if you generated the compiler api through swig)

**Comment by chuckyount** [comment]
I believe this is fixed in v2
