### ISSUE TITLE
Change "any" to "many" in first paragraph of README

### ISSUE THREAD

**Issue by rgesteve** [intel/yask#50]
Sorry for the pettiness of this issue, but I believe that good descriptions are helpful:  the first paragraph of the README reads: "YASK--Yet Another Stencil Kernel: A framework to facilitate exploration of the HPC stencil-performance design space, including **any** optimizations such as...".  Should it not be, instead "including **many** optimizations" ?

I hope this is useful.  Thank you for your wonderful work!

**Comment by chuckyount** [comment]
Thanks for finding the typo!
