### ISSUE TITLE
Large performance difference between running from yask.sh and executable

### ISSUE THREAD

**Issue by zohourih** [intel/yask#81]
Hi,

I am evaluating your framework on a machine with a socketed Xeon Phi 7210F and the MCDRAM configured in the default cache mode. I compiled the 3axis stencil by using the following command:

`make clean; make stencil=3axis arch=knl`

If I run the stencil using yask.sh, I get the following results:

```
bin/yask.sh -stencil 3axis -arch knl -d 512 -t 1:

best-throughput (est-FLOPS):       138.865G
```

However, running the same stencil directly using the executable with the same settings results in significantly lower performance:

```
bin/yask_kernel.3axis.knl.exe -d 512 -t 1:

best-throughput (est-FLOPS):       31.4167G
```

Is there a specific reason for this? Should I always run from the sh file?

**Comment by chuckyount** [comment]
Thanks for your interest in YASK.

Are you sure the Xeon Phi is in cache mode? The yask.sh script only works by default in flat mode, and it uses a numactl command to give you the performance difference shown. Can you send me the log file (from the logs dir) from the yask.sh run? (The log file is created by the script.)

Chuck Y

**Comment by zohourih** [comment]
Thank you for your reply. Actually I am not sure about the configuration of the device, since I didn't set up the machine. However, the person who set up the machine said he has not changed the configuration from default, and apparently the default configuration for MCDRAM is cache mode. I could be wrong, though.

I have attached the log from the sh run, and also the output from the exe run that was captured manually.

[yask.exe.log](https://github.com/intel/yask/files/1668412/yask.exe.log)
[yask.sh.log](https://github.com/intel/yask/files/1668413/yask.sh.log)

**Comment by chuckyount** [comment]
This KNL is in flat mode. You can see this from the following lines in the shell-script’s log file:

+ numactl -H
available: 2 nodes (0-1)

This explains why the shell command works better. You should get similar results by putting ‘numactl --preferred=1’ in front of the executable.

Chuck

**Comment by zohourih** [comment]
I see. Then that means our device is actually in flat mode. Using "numactl --preferred=1" before the executable does indeed result in the same performance as running via the sh script.

Thank you for your help. This ticket can be closed.
