### ISSUE TITLE
Boundary condition for 3axis

### ISSUE THREAD

**Issue by zohourih** [intel/yask#83]
Can you kindly elaborate how the boundary condition for the 3axis stencil is handled? By boundary condition I mean the neighbors of cells on the grid boundaries that fall outside of the gird. From the WOLFHPC16 slides it seems that the allocated grid is (2 * radius) points bigger than the problem domain in each dimension, allowing such neighbors to be read from a valid memory address. Is this correct? If yes, am I correct to say that the input size that we set in YASK is the actual problem size, but the size of the grid that is allocated in memory is bigger due to these out-of-bound neighbors?

**Comment by chuckyount** [comment]
Yes, a halo size is allocated outside the working domain area. This is explained in more detail in the API documentation. Run ‘make docs’ and open the generated index.html file for more information.

Chuck
